language: python
python:
- '3.7'

dist: bionic

env:
  global:
    - BS_PIP_ALLOWED=1
    - BS_ECHO_DEBUG=1
    - STATE=monitoring
  matrix:
    - SALT_ARGS="-l debug --local --retcode-passthrough --pillar-root=.salt/pillar --file-root=$PWD"


before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo -E sh -s -x python3.7 -- stable

install:
  - sudo mkdir -p /srv && sudo ln -sfn $PWD /srv/formula
  # Show the loaded pillars since the states are generally depending on this
  - sudo salt-call pillar.items $SALT_ARGS
  # See what kind of travis box you're on to help with making your states
  # compatible with travis
  - sudo salt-call grains.items $SALT_ARGS

script:
  # Todo: Linting check of SLS / XML
  - sudo -E salt-call state.show_sls $STATE $SALT_ARGS
  - sudo -E salt-call state.sls $STATE $SALT_ARGS

  # Idempotence check
  - sudo -E salt-call state.sls $STATE $SALT_ARGS > /tmp/second
  - cat /tmp/second
  - bash -c '! grep -q "^Not Run:" /tmp/second'
